cxf.path: /api
server.port: 8089

esb:
  port: 8088
  basePath: /api
  host: localhost

rest:
  host: localhost
  port: 8080
  basePath: /api

soap.serviceAddress: http://192.168.0.7:8082/soap-service/PurchaseOrder

ftp:
  host: 192.168.0.7
  port: 21
  path: /
  username: user
  password: pass

monitoring:
  sleep: 100
  bufferSize: 10000000

db:
  username: postgres
  password: password
  url: jdbc:postgresql://192.168.0.3:5432/postgres
  driverClassName: org.postgresql.Driver