version: '2'
services:
  ftp:
    build: ftp/
    ports: 
      - "21:21"
      - "30000-30009:30000-30009"
    environment: 
      PUBLICHOST: localhost
  postgresql:
    build: postgresql/
    ports: 
      - "5432:5432"
    environment: 
      POSTGRES_PASSWORD: password
  activemq:
    build: activemq/
    ports: 
      - "8161:8161"
      - "61616:61616"
      - "61613:61613"
    environment: 
      ACTIVEMQ_ADMIN_LOGIN: admin
      ACTIVEMQ_ADMIN_PASSWORD: admin
  rest:
    build: rest/
    ports: 
      - "8080:8080"
  soap:
    build: soap/
    ports:
      - "8081:8081"
      - "8082:8080"